# Generated by Django 4.0.6 on 2022-08-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.CharField(max_length=10, verbose_name='權重')),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_train_loss', models.FloatField(verbose_name='box_train_loss')),
                ('box_value_loss', models.FloatField(verbose_name='box_value_loss')),
                ('obj_train_loss', models.FloatField(verbose_name='obj_train_loss')),
                ('obj_value_loss', models.FloatField(verbose_name='obj_value_loss')),
                ('cls_train_loss', models.FloatField(verbose_name='cls_train_loss')),
                ('cls_value_loss', models.FloatField(verbose_name='cls_value_loss')),
                ('precision', models.FloatField(verbose_name='準確度')),
                ('recall', models.FloatField(verbose_name='召回率')),
                ('mAP_05', models.FloatField(verbose_name='mAP_0.5')),
                ('mAP_05_095', models.FloatField(verbose_name='mAP_0.5:0.95')),
                ('x_lr0', models.FloatField(verbose_name=' x/lr0')),
                ('x_lr1', models.FloatField(verbose_name=' x/lr1')),
                ('x_lr2', models.FloatField(verbose_name=' x/lr2')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.weight')),
            ],
        ),
    ]
